# gate.id=1
# spring.datasource.url=jdbc:mysql://avnadmin:AVNS_F2T1_qcY8GrmjVCi1Is@mysql-34a04078-nguyennguyen672004-d578.j.aivencloud.com:18758/defaultdb?ssl-mode=REQUIRED
# spring.datasource.username=
# spring.datasource.password=AVNS_F2T1_qcY8GrmjVCi1Is
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Thông tin Cổng
gate.id=1
# Cấu hình Database
db.url=jdbc:mysql://avnadmin:AVNS_F2T1_qcY8GrmjVCi1Is@mysql-34a04078-nguyennguyen672004-d578.j.aivencloud.com:18758/defaultdb?ssl-mode=REQUIRED
db.user=avnadmin
db.password=AVNS_F2T1_qcY8GrmjVCi1Is

# Cấu hình các cổng khác (Để trống nếu chỉ chạy 1 cổng)
peer.servers=

# Sau khi enter các lệnh trên, bạn có thể chạy file Java
# (Dùng phím mũi tên lên để gọi lại cái dòng lệnh chạy java rất dài của bạn và Enter)